Init
gtngzlv/gophermart pull request #1
Opened 2023-08-10 15:28 UTC by gtngzlv

2023-08-21 16:05 UTC, valentinsoe requested changes
Спасибо за вовремя сданную работу.
Много замечаний написал по ходу PR.

Не до конца посмотрел часть про БД, репозитории, сейчас напишу почему.
Мне не очень понятна схема, у нас нет указания, что идентификаторы заказов на начисление и списание перескаются. Поэтому не стоит их хранить в одном месте.
Также мне непонятно логика уменьшения баланса accrual, при списании. Это приведет к тому, что в истории заказов на начисление - поменяется сумма начисления заказа.
И в целом "атомарность" многих операций под вопросом.
Еще из замечаний - работы с многопоточностью для получения статус заказа из системы лояльности(из ненаписанного в коде)

Если у нас 10 воркеров, то загружать для них 10 заданий достаточно странно. Если хоть один из них "подвиснет", все остальные воркеры будут его ждать. Заданий кажется должно быть больше, чем воркеров.
Туда же - если мы всегда выбираем заказы по принципу "самые старые 10", то если в системе лояльности по этим 10 будет долго выполняться расчет - наши воркеры даже не попытаются проверить статусы более новых заказов.
Еще один пункт - зачем нам ожидать окончания проверки статусов всей загруженной партии заказов перед тем как запросить в БД новую? Это потенциально бутылочное горлышко в производительности.

2023-08-21 16:05 UTC, valentinsoe commented on internal/auth/middleware.go
> +		if _, ok := allowList[r.URL.Path]; ok {
Лучше сгруппировать в роутере маршруты которым нужна эта middleware, а которым нет.
Иначе маршруты захардкожены и здесь и в роутере. Что не очень хорошо.

Проверять URL - не ответсвенность Middleware. Какие middleware применять к какому пути - ответственность роутера

2023-08-21 16:05 UTC, valentinsoe commented on internal/auth/middleware.go
> +const cookieName cookie = "authToken"
Константу, структуру  "клеймов",  я бы оформил как функцию и отнес в файл auth.go. Чтобы только он зависел от пакета jwt и все константы/структуры были в нем.

2023-08-21 16:05 UTC, valentinsoe commented on internal/auth/middleware.go
> +			if errors.Is(err, jwt.ErrSignatureInvalid) {
Кажется это лишний if, все равно вернем 401

2023-08-21 16:05 UTC, valentinsoe commented on internal/auth/middleware.go
> +		ctx := context.WithValue(r.Context(), cookieName, claim)
Нам точно нужно все "клеймы" писать в контекст? Кажется логина будет достаточно.

2023-08-21 16:05 UTC, valentinsoe commented on internal/client/accrual.go
> +		wg.Add(len(orderList))
Не могу сказать, что так работать не будет, но workGroup предназначен для ожидания завершения горутин. А не ожидания завершения итерации.
Для этого обычно используется канал в который пишутся результаты обработки.

2023-08-21 16:05 UTC, valentinsoe commented on internal/client/accrual.go
> +func (a *accrualClient) GetOrderByNumber(orderNum string) (*model.GetOrderAccrual, error) {
Предложил бы разделить на две части этот файл. 
В одной у нас сервис, который ведает горутинами, обновлением базы и т.д. 
В другой же только код представляющий реализацию обращения к внешнему сервису.

2023-08-21 16:05 UTC, valentinsoe commented on internal/client/accrual.go
> +		_, err = fmt.Sscanf(tooManyRequestTemplate, string(resBody), &rl)
Если текст сообщения об ошибке от сервиса поменяется - то мы либо будем игнорировать эту ошибку, либо навсегда останемся с когда-то давно полученным лимитом.

Лучше предусмотреть логику на этот счет отдельно.

2023-08-21 16:05 UTC, valentinsoe commented on internal/core/auth.go
Лишний файл?

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/init.go
> +	h.Router.Use(auth.Authorization)
В требованиях у нас клиент может поддерживать запросы со сжатием.

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/init.go
> +	h.Router.Post("/api/user/balance/withdraw", h.WithdrawLoyalty)
Занудство - WithdrawLoyalty - "отозвать свою лояльность" :)

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/orders.go
> +	if err = goluhn.Validate(orderNum); err != nil {
Если есть свободное время, рекомендую посмотреть на реализацию алгоритма Луна

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/orders.go
> +	if existingOrder != nil && existingOrder.UserID != userInfo.ID {
Если хранить в токене userId, а не логин, то не придется отдельно лазить за пользователем в БД для этой проверки.

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/orders.go
> +	if err = h.repo.LoadOrder(orderNum, *user); err != nil {
Это и предыдущее обращение в БД выполняются не в рамках транзакции. А значит у нас не гарантии, что за это время "другой" пользователь не зарегистрировал свой заказ.
Либо http.StatusOK надо возвращать в предыдущем условии, когда заказ есть от этого же пользователя, либо надо это делать в рамках единой транзакции

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/user.go
> +	buf := bytes.NewBuffer(body)
Если мы уже считали весь body, зачем мы создаем буффер и потоково его декодируем?
Либо не читать целиком, либо использовать json.Unmarshal.

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/user.go
> +		h.log.Errorf("Login: incorrect username/password, %s", err)
Кажется это может быть не единственной причиной ошибки, а пользователю мы скажем что неверные логин и пароль.

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/user.go
> +		cryptedPsw, err := utils.HashString(u.Password)
При проверке пароля - хэширование выполняется на уровне репозитория. При создании пользователя - на уровне хендлера. Лучше чтобы было в одном месте(не на уровне репозитория :) )

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/user.go
> +	user, err := h.repo.GetUserByLogin(login)
Мы не доверяем токену, что проверяем наличие пользователя в БД каждый раз?:)

2023-08-21 16:05 UTC, valentinsoe commented on internal/handlers/orders.go
> +	user, err := h.repo.GetUserByLogin(userInfo.Login)
Мы уже сделали getUserInfoByToken, зачем мы еще раз получаем информацию о пользователе в рамках одного HTTP-запроса?

2023-08-21 16:05 UTC, valentinsoe commented on migrations/20230808152847_db_init.sql
> +    NUMBER BIGINT UNIQUE NOT NULL,
Номер заказа не стоит хранить в формате числа. Номер заказа - строка.

2023-08-21 16:05 UTC, valentinsoe commented on migrations/20230808152847_db_init.sql
> +    ORDER_NUMBER BIGINT PRIMARY KEY,
Не хватает суррогатного ключа. ORDER_NUMBER лучше быть строкой, и не быть первичным ключом.

2023-08-21 16:05 UTC, valentinsoe commented on migrations/20230808152847_db_init.sql
> +    USER_ID INT NOT NULL,
В заказах уже есть USER_ID, не стоит его дублировать.

2023-08-27 19:53 UTC, gtngzlv commented on internal/handlers/orders.go
> +	if existingOrder != nil && existingOrder.UserID != userInfo.ID {
Тогда придется лезть в БД за логином при попытке регистрации, как лучше поступить? Хранить в структуре клеймов и логин и userid?

2023-08-27 20:13 UTC, gtngzlv commented on internal/handlers/user.go
> +	user, err := h.repo.GetUserByLogin(login)
Тут скорее нужна функция для получения ID и Login в рамках одной структуры, потом эти значения переиспользуются в других функциях

2023-08-28 07:38 UTC, gtngzlv commented on internal/client/accrual.go
> +		_, err = fmt.Sscanf(tooManyRequestTemplate, string(resBody), &rl)
Вынесу вопрос на 1-2-1

2023-08-28 07:38 UTC, gtngzlv commented on internal/client/accrual.go
> +		wg.Add(len(orderList))
Вынесу вопрос на 1-2-1

2023-08-29 19:12 UTC, valentinsoe requested changes
Спасибо за исправления!
Пока исправлены не совсем все замечания.
Работа кажется немного в "переходном" состоянии:)

2023-08-29 19:12 UTC, valentinsoe commented on internal/auth/auth.go
> +	claim := returnNewClaims()
Не понял сути изменения:) Если функция возвращает пустую структуру, то просто инициализатор выглядит лучше

2023-08-29 19:12 UTC, valentinsoe commented on internal/auth/middleware.go
> +		ctx := context.WithValue(r.Context(), loginCookie, claim.Login)
Название loginCookie - вводит немного в заблуждение. Это же не кука, а просто логин "выковырянный из куки"

2023-08-29 19:12 UTC, valentinsoe commented on internal/auth/middleware.go
> +		claim := returnNewClaims()
Мелкое занудство. claim - не очень корректно, это все-таки claims - как следует и из названия типа и из названия функции:)

2023-08-29 19:12 UTC, valentinsoe commented on internal/client/client.go
> +func NewAccrualProcessing(db *repository.Repository, host string, poolSize int) *accrualClient {
Позанудствую еще немного. 
Предлагают отделить клиента от процессора. Клиент только делает HTTP-запросы и разбирает ответы, реализует rate.Limiter.
Всю остальную логику уже делает процессинг(запускает воркеры, обновляет БД и т.д.). 

Такое разделение легко позволяет подменить клиент на какую-то "моковую" реализацию, если внешний сервис недоступен для отладки/тестов.

2023-08-29 19:12 UTC, valentinsoe commented on internal/handlers/orders.go
> +	if existingOrder != nil && existingOrder.UserID != userInfo.ID {
Не до конца понял. При попытке регистрации нам не приходит токен, а приходит логин и пароль. За ними лезть никуда не надо:)

2023-08-29 19:12 UTC, valentinsoe commented on migrations/20230808152847_db_init.sql
> +    BALANCE FLOAT DEFAULT 0 NOT NULL
Мы к пользователю добавили баланс, но не добавили сумму списанных с его счета средств.

2023-09-04 10:12 UTC, gtngzlv commented on internal/auth/auth.go
> +	claim := returnNewClaims()
в ЯП курсе инициализация claim-ов была через объявление нового экземпляра структуры, как я и написала до этого. Пожалуй, верну как было :)

2023-09-04 10:15 UTC, gtngzlv commented on migrations/20230808152847_db_init.sql
> +    BALANCE FLOAT DEFAULT 0 NOT NULL
Сумма считается по типу sum(amount) from orders where operation_type=withdrawal and user_id=$1

2023-09-05 19:42 UTC, valentinsoe commented on migrations/20230808152847_db_init.sql
> +    BALANCE FLOAT DEFAULT 0 NOT NULL
Кажется странным что одна сумма считается так, а другая хранится:)

2023-09-05 20:02 UTC, valentinsoe requested changes
Спасибо за исправления.
Как поправить работу с Mutex - написал.

Чего все еще не хватает - это транзакционности, что позволяет обойти некоторые условия системы.
Все еще можно загнать баланс в минус отправив два одновременных запроса, потмоу что проверка достаточности баланса и списание происходит в двух отдельных транзакциях.

Не знаю сколько  времени ты можешь тратить на задание. Но если есть возможность рекомендую отдельно выделить слой бизнес-логики, то есть стоит разделять подобным образом:
1) Слой хендлеров. Тут мы только разбираем запрос и формируем ответ.
2) Слой бизнес-логики. Тут мы выполняем всю логику, то есть проверки, выполнение нескольких действий с БД.
3) Слой БД - набор функций, каждая из которых выполняет один запрос к БД.

2023-09-05 20:02 UTC, valentinsoe commented on internal/client/client.go
> +		b := a.rw.TryLock()
Вероятность того, что в этот момент времени нет ни одного readlock - может быть далека от 1.
Проверять подобным образом не стоит.
Чтобы избежать того, чтобы каждая горутина спала указанное в заголовке время - нужно сделать сон не относительным, а абсолютным. 
До получения блокировки - высчитываем абсолютное время до которого надо спать. А после получения блокировки  - спим до него

2023-09-14 13:09 UTC, gtngzlv commented
Мне очень нужна помощь с go vet, потому что я пробовала в 10 разных мест вставить закрытие res.Body, но ему не подходит ни одно...

2023-09-15 05:28 UTC, valentinsoe requested changes
Спасибо за исправления.
C мьютексами все еще какая-то путаница.
На вопрос про линтер ответил.

2023-09-15 05:28 UTC, valentinsoe commented on internal/client/client.go
> +		lock := a.m.TryLock()
Добавлять второй мьютекс со TryLock не надо. Будет такая же проблема как и раньше. Просто RWMutex надо блокировать и все. И использовать абсолютное время.

2023-09-15 05:28 UTC, valentinsoe commented on internal/client/client.go
> +				duration := returnRetryDuration(res)
go vet ругается из-за этого. Ты "передаешь" res в другую горутину, линтер недостаточно умен чтобы отследить что ты там с ним делаешь.

2023-09-15 09:30 UTC, gtngzlv commented on internal/client/client.go
> +		lock := a.m.TryLock()
Если мы про time.sleep - там абсолютное время. секунды берутся из заголовка в ответе

2023-09-19 08:46 UTC, valentinsoe approved these changes
Спасибо за исправления.

Касательно транзакционности. При текущей ее реализации - у тебя бизнес-логика проросла на слой хранения данных. Обращения к базе лучше делать простыми, а управлять транзакциями с уровня "выше".

Вот например аккуратный способ это сделать.
https://www.kaznacheev.me/posts/en/clean-transactions-in-hexagon/

2023-09-19 08:46 UTC, valentinsoe commented on SPECIFICATION.md
Комментарий 1. Не делай пожалуйста force push того, что уже отправлено на проверку.
Я не могу посмотреть только "новые" изменения теперь.

Это в целом и на рабочую практику стоит распространить. Если код отдан на ревью, то форс-пушить уже не надо.
Если переживаешь за то что слишком много коммитов, можно сделать squash commits and merge в мастер. Тогда в мастер-ветке история будет "чистой"

2023-09-19 12:28 UTC, merged